---
- tags: [neovim]
  block:
    - name: Install neovim
      package:
        name: "{{ neovim_packages }}"
        state: present

    - name: Gather facts about user for whom neovim shall be configured
      getent:
        database: passwd
        key: "{{ neovim_user_id }}"
        split: ~

    - name: Create neovim directory for autoloading configurations
      file:
        path: "{{ neovim_autoload_dir }}"
        state: directory
        recurse: yes
        mode: 0o700
        owner: "{{ neovim_user_id }}"
      when: neovim_plugins

    - name: Install vim-plug
      get_url:
        url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
        dest: "{{ neovim_autoload_dir }}/plug.vim"
        mode: 0o600
        owner: "{{ neovim_user_id }}"
      when: neovim_plugins

    - name: Create base directory for configurations of neovim
      file:
        path: "{{ neovim_config_dir }}"
        state: directory
        mode: 0o700
        owner: "{{ neovim_user_id }}"

    - name: Configure neovim
      template:
        src: init.vim
        dest: "{{ neovim_config_file }}"
        mode: 0o600
        owner: "{{ neovim_user_id }}"
